[tool.poetry]
name = "tcode-api"
version = "0.1.0"
description = "TCode API specification implemented in pydantic"
authors = ["Connor Novak <connor@trilo.bio>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
