[project]
name = "tcode-api"
version = "1.16.0"
description = "TCode API specification implemented in pydantic"
authors = [
    { name = "Connor Novak", email = "connor@trilo.bio" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.15.0",  # Installed to ensure type checking of pydantic
    "pydantic>=2.10.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
plugins = ['pydantic.mypy']

[dependency-groups]
dev = [
    "coverage>=7.8.2",
]


[tool.coverage.run]
branch = true
command_line = "-m unittest discover -s tests"
omit = [
  "tests/*",
  "__init__.py",
]
