[project]
name = "tcode-api"
version = "1.10.1"
description = "TCode API specification implemented in pydantic"
authors = [
    { name = "Connor Novak", email = "connor@trilo.bio" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ipython>=9.1.0",
    "isort>=6.0.1",
    "mypy>=1.15.0",  # Installed to ensure type checking of pydantic
    "ruff>=0.11.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
plugins = ['pydantic.mypy']
# https://adamj.eu/tech/2021/05/25/python-type-hints-specific-type-ignore/
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true

[tool.ruff]
line-length = 100
