[project]
name = "tcode-api"
version = "1.4.0"
description = "TCode API specification implemented in pydantic"
authors = [
    { name = "Connor Novak", email = "connor@trilo.bio" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
